//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDISApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalConditions
    {
        public string Afectiune { get; set; }
        public System.DateTime Data { get; set; }
        public string Patient_UID { get; set; }
        public System.Guid Entry_UID { get; set; }
    }
}
