//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDISApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public long CNP { get; set; }
        public string Adresa { get; set; }
        public System.DateTime Data_nasterii { get; set; }
        public byte Varsta { get; set; }
        public string Email { get; set; }
        public System.Guid UID { get; set; }
    }
}
